ALTER TABLE hl_trades SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('hl_trades', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE hl_l2book SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('hl_l2book', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE hl_asset_ctx SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('hl_asset_ctx', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE hl_candles SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin,interval', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('hl_candles', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE hl_rest_candles SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin,interval', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('hl_rest_candles', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE hl_rest_funding SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('hl_rest_funding', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_agg_trades SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_agg_trades', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_depth SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_depth', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_mark_price SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_mark_price', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_liquidations SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC,event_hash');
SELECT add_compression_policy('bn_liquidations', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_tickers SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC,update_id,event_hash');
SELECT add_compression_policy('bn_tickers', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_klines SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol,interval,contract_type,pair', timescaledb.compress_orderby = 'time DESC,event_hash');
SELECT add_compression_policy('bn_klines', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_funding SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_funding', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_oi SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_oi', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_oi_hist SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol,period', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_oi_hist', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_ls_top_pos SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol,period', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_ls_top_pos', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_ls_top_acc SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol,period', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_ls_top_acc', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_ls_global SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol,period', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_ls_global', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_taker_vol SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol,period,contract_type', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_taker_vol', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_premium SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_premium', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_basis SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,pair,period,contract_type', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_basis', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_funding_info SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_funding_info', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_delivery SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,pair', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_delivery', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_exchange_info SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_exchange_info', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE bn_rest_constituents SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('bn_rest_constituents', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE news SET (timescaledb.compress, timescaledb.compress_segmentby = 'source', timescaledb.compress_orderby = 'time DESC,dedup_url');
SELECT add_compression_policy('news', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE news_sentiment SET (timescaledb.compress, timescaledb.compress_segmentby = 'source', timescaledb.compress_orderby = 'time DESC,dedup_url');
SELECT add_compression_policy('news_sentiment', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE fred_data SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,series_id', timescaledb.compress_orderby = 'time DESC,release_id');
SELECT add_compression_policy('fred_data', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE fear_greed SET (timescaledb.compress, timescaledb.compress_segmentby = 'source', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('fear_greed', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE cc_exchange_vol SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,exchange', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('cc_exchange_vol', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE cc_price SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('cc_price', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE finnhub_quotes SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,symbol', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('finnhub_quotes', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE market_status SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,exchange', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('market_status', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE s3_trades SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('s3_trades', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
ALTER TABLE s3_l2book SET (timescaledb.compress, timescaledb.compress_segmentby = 'source,coin', timescaledb.compress_orderby = 'time DESC');
SELECT add_compression_policy('s3_l2book', compress_after => INTERVAL '48 hours', if_not_exists => TRUE);
